### ISSUE TITLE
Old plugins.json items seem to be cached somewhere, still appear on the Toolbox UI

### ISSUE THREAD

**Issue by jeremychone** [sketchplugins/plugin-directory#103]
When I did my first plugins.json pull request, I gave the wrong name: 

```json
    {
        "description": "Turn your artboards into storyboards.",
        "name": "Storyboard",
        "owner": "BriteSnow"
    }
```

Once it got merged, I realized I did a mistake on the name, so, I did another pull request that got merged with: 

```json
    {
        "description": "Turn your artboards into storyboards.",
        "name": "sketch-storyboard",
        "owner": "BriteSnow"
    }
```

So, this is perfect, except that at least on my local Toolbox, I still see the first entry (even if it does not exist in the plugins.json anymore). 

![image](https://cloud.githubusercontent.com/assets/74671/6692916/d62a55a6-cc8c-11e4-84d0-ebf96bf8b36b.png)

## Expected result

It should show only the second item, as it is the one correctly specified in the plugins.json

**Comment by jeremychone** [comment]
Ok, the good news is that it just seems for me. I asked a friend to check its Toolbox (after the correct "Sketch Storybard" was updated), and it just see the correct item (the second one). 

So, it's probably a client caching issue. No critical one to fix.

**Comment by bomberstudios** [comment]
Anyway, you should file this issue in https://github.com/buzzfeed/Sketch-Toolbox/issues : )

**Comment by jeremychone** [comment]
Ho yes, wrong one. Sorry about this.
