### ISSUE TITLE
ColorMime for generating color palletes in sketch using colourlovers.com

### ISSUE THREAD

**Issue by jtmarmon** [sketchplugins/plugin-directory#106]
Link: [https://github.com/jtmarmon/ColorMime](https://github.com/jtmarmon/ColorMime)
Demo: [https://www.youtube.com/watch?v=yloLDmNfpDM](https://www.youtube.com/watch?v=yloLDmNfpDM)

**Comment by bomberstudios** [comment]
Plugin was already in the list (added in b3084f455ac09359c7fb5688521fe2ed0f488a2a)

**Comment by jtmarmon** [comment]
oh weird. I swear I didn't see it when I ctrl + f'd. sorry about that
