### ISSUE TITLE
marketch

### ISSUE THREAD

**Issue by tudou527** [sketchplugins/plugin-directory#122]
Marketch is a Sketch 3 plug-in for automatically generating html page that can measure and get CSS styles on it.

https://github.com/tudou527/marketch/tree/master

**Comment by bomberstudios** [comment]
Plugin looks very promising, but you seem to have removed the code from the repository?

**Comment by tudou527** [comment]
sorry i rename plugin name to "marketch"。the repository is [https://github.com/tudou527/marketch/tree/master](https://github.com/tudou527/marketch/tree/master)

**Comment by bomberstudios** [comment]
I know, I know, but still the code doesn't seem to be there in the repo. It looks like you are using a git submodule, but the code inside that is not uploaded anywhere and the .gitmodules file is also missing from your repo.

**Comment by tudou527** [comment]
sorry, code update done, is that ok ? ( y i'm so stupid! )

**Comment by bomberstudios** [comment]
It's fine now : )
