### ISSUE TITLE
tisho/sketch-plugins - deprecated.

### ISSUE THREAD

**Issue by Chrisedmo** [sketchplugins/plugin-directory#125]
I was just browsing this amazing list and found one that has been deprecated - so should it be removed?

**Comment by bomberstudios** [comment]
Interesting question… it makes sense to remove it, but we should ask him what he thinks, since he should have the last word : )

Ping @tisho for comments!

**Comment by tisho** [comment]
Yup, I think it makes sense to remove it.

**Comment by bomberstudios** [comment]
Great, let's kick it then : )
