### ISSUE TITLE
matt-curtis/Archetype

### ISSUE THREAD

**Issue by matt-curtis** [sketchplugins/plugin-directory#130]
https://github.com/matt-curtis/Archetype

Archetype is an experimental Sketch Plugin for adaptive and responsive layouts. It's something I put together made in my free time as one of several plugin ideas I'm working on regarding Sketch. It basically allows you to use CSS to layout elements in Sketch.

**Comment by bomberstudios** [comment]
Archetype was already on the list, closing : )
