### ISSUE TITLE
Include description for my plugin

### ISSUE THREAD

**Issue by eaugustine** [sketchplugins/plugin-directory#1300]
Hi! How can I get the description for my plugin to show up? I have added the description into my package.json file and updated the plugin, but it still shows without a description in the plugin directory's README file and plugins.json file.

**Comment by bomberstudios** [comment]
Hi there. We don’t read the description automatically from the `package.json` file yet. You can open a PR adding the description to `plugins.json`, and it will be picked up by the README and the plugin directory.

Alternatively, feel free to post the description and identifier of your plugin here and I’ll make the necessary changes myself.

**Comment by bomberstudios** [comment]
I had a spare minute and I added the description from your `package.json`. Thanks for your plugin!

**Comment by eaugustine** [comment]
Thank you!
