### ISSUE TITLE
Automate-Sketch

### ISSUE THREAD

**Issue by Ashung** [sketchplugins/plugin-directory#170]
https://github.com/Ashung/Automate-Sketch/

- Add Space Between CJK and Western Character
- Change Typeface for the Latin character set
- Artboard Form Group
- Artboard Form Layers
- Clear Slices
- New Layer Base Slice
- Clean Layer Name
- Clear Guides

**Comment by bomberstudios** [comment]
This was added in ef33dc256172b4353349a426cfd840c1eebcf31f, a few days ago : )
