### ISSUE TITLE
good place for beginner tutorials?

### ISSUE THREAD

**Issue by corysimmons** [sketchplugins/plugin-directory#186]
Plenty of projects, but not a lot of tutorials that I can find.

Any suggestions on where to start? Already on http://developer.sketchapp.com/

**Comment by bomberstudios** [comment]
Ask again on http://sketchplugins.com, this is just a Plugins repository : )

**Comment by corysimmons** [comment]
crap i never figured out how to use mailing lists. o well, thnx!
