### ISSUE TITLE
Qordoba for Sketch

### ISSUE THREAD

**Issue by qordobagit** [sketchplugins/plugin-directory#193]
Qordoba’s Sketch plugin allows designers to translate their mockups to other languages, making product internationalization easier.

https://github.com/Qordobacode/qordoba-for-sketch

**Comment by bomberstudios** [comment]
Added, thanks for the link : )

**Comment by wassemgtk** [comment]
Can you please update the description to: Qordoba’s Sketch plugin allows designers to translate their mockups to other languages, making product internationalization easier.

**Comment by bomberstudios** [comment]
Will do, but if you update your repo description it will be picked up automatically if we ever rebuild the JSON file : )

**Comment by wassemgtk** [comment]
Sure :) updated.

Thanks
