### ISSUE TITLE
Here is an issue...

### ISSUE THREAD

**Issue by jkinley-sds** [sketchplugins/plugin-directory#224]
The plugin generates code, but I get this error when I process my scss. Also, I can't figure out how to use the generated code. An example please?

<img width="580" alt="screen shot 2016-05-26 at 2 14 43 pm" src="https://cloud.githubusercontent.com/assets/19417886/15590391/63e43b7a-234c-11e6-91e9-e15673340aff.png">

**Comment by bomberstudios** [comment]
Hi there,

this repo is just a directory of Plugins. If you need help with a specific Plugin, please contact its developer(s) : )
