### ISSUE TITLE
Optically Sketch Plugin

### ISSUE THREAD

**Issue by vmdanilov** [sketchplugins/plugin-directory#225]
Automated and mathematically precise optical adjustments in Sketch.

[http://designplugins.com/optically](http://designplugins.com/optically)

**Comment by vmdanilov** [comment]
@bomberstudios is there a problem with not hosting on GitHub? I've created [this repo](https://github.com/vmdanilov/optically-sketch-plugin) with description and can submit a PR.

**Comment by bomberstudios** [comment]
Not really. The only "problem" is that I have a script that does the work automatically for GH-hosted projects, and I can't use it for yours, so it needs to be done manually, and that takes time, and…

Give me 5 minutes : )

**Comment by vmdanilov** [comment]
OK, cool :) I've seen the script. That's why I though the repo could help. Thanks, BTW.
