### ISSUE TITLE
New Plugin: Export More...

### ISSUE THREAD

**Issue by nathco** [sketchplugins/plugin-directory#264]
**Export More** is a new and improved plugin adding export support for Apple Icon Image ( .icns ) and Animated GIF ( .gif ) file formats. Based on my previous [Generate ICNS](http://github.com/nathco/Generate-ICNS) and [Generate GIF](http://github.com/nathco/Generate-GIF) plugins…

https://github.com/nathco/Export-More

**Comment by bomberstudios** [comment]
Added it on cf899b5e7cc64fdf8f54995d5da036302ca2a89b, so closing! : )
