### ISSUE TITLE
Sketch CodeFlow

### ISSUE THREAD

**Issue by KjellConnelly** [sketchplugins/plugin-directory#265]
Sketch CodeFlow by Pop Pop LLC
Turn artboards into code.

Current version exports iOS Objective-C UIKit Code only. More to come!

http://www.sketchcodeflow.com

![banner](https://cloud.githubusercontent.com/assets/13230597/18562816/2f615c52-7b3a-11e6-800b-064350e11320.png)

**Comment by bomberstudios** [comment]
I think I can't add a Plugin to the directory if it doesn't have a GitHub URL for the download (or rather: last time I tried, Sketch Toolbox broke horribly). I'll see what I can do anyway.
