### ISSUE TITLE
3 new plugins: Copy Paste Position Size, Keyboard Resize & Resize Commands

### ISSUE THREAD

**Issue by ajilderda** [sketchplugins/plugin-directory#268]
Hi @bomberstudios, 

Can you please add these 3 plugins to the list? Thanks in advance! 🎉 

- **[Copy Paste Position & Size](https://github.com/ANGIstudio/Copy-Paste-Position-Size)**
 A Sketch plugin that lets you easily copy & paste width, height, x & y values from and to objects

- **[Keyboard Resize](https://github.com/ANGIstudio/Keyboard-Resize)**
A Sketch plugin that lets you resize objects from all sides with keyboard shortcuts. As a bonus you can specify the resize amount.

- **[Resize Commands](https://github.com/ANGIstudio/Resize-Commands)**
A Sketch plugin that lets you resize and reposition objects by using simple arithmetic commands, like `b+20,lr+20`

**Comment by ajilderda** [comment]
I've just updated the links to (old links still work though):
https://github.com/ANGIstudio/Sketch-Resize-Commands
https://github.com/ANGIstudio/Sketch-Copy-Paste-Position-Size
https://github.com/ANGIstudio/Sketch-Keyboard-Resize

**Comment by bomberstudios** [comment]
Added, thanks : )
