### ISSUE TITLE
Symbol Organizer plugin

### ISSUE THREAD

**Issue by sonburn** [sketchplugins/plugin-directory#277]
Plugin to organize your symbols page and layer list, based on the symbol names. Also provides the ability to layout symbols horizontally or vertically, and reverse the alphabetical sort order of the layer list.

https://github.com/sonburn/symbol-organizer

**Comment by bomberstudios** [comment]
Plugin is already on the list: https://github.com/sketchplugins/plugin-directory/commit/f14a35eaa5f3b7e213304f5c142c28b7c8235e91 : )

**Comment by sonburn** [comment]
Ha, I didn't even bother to look... as it's my plugin and I never submitted it. Cool beans, thanks!
