### ISSUE TITLE
Sketch-Color-Vars

### ISSUE THREAD

**Issue by philsinatra** [sketchplugins/plugin-directory#287]
I'd like to add this plugin to the repository:

# Sketch Color Vars

A Sketch plugin that will export the fill color of selected layers to SCSS, LESS and CSS files.

[https://github.com/philsinatra/Sketch-Color-Vars](https://github.com/philsinatra/Sketch-Color-Vars)

**Comment by bomberstudios** [comment]
Added, thanks for the submission : )
