### ISSUE TITLE
Add Category by Sketch compatible version

### ISSUE THREAD

**Issue by caiocall** [sketchplugins/plugin-directory#301]
Hi! This is an amazing sketch plugin repository, very well done. I appreciate your work!

I tried downloading and using a few plugins and I noticed most of them are not working with the latest version of Sketch Version 41.2 (35397). I would like to suggest you to add a version category where users could help by saying what plugins are currently working on each version so it can be easier to find the plugins working for each version, that could help a lot and save others time when finding new plugins.

Keep the good work! Thanks.

**Comment by bomberstudios** [comment]
Thanks for the feedback. There is already a way for plugins to specify which version of Sketch they work with, but we haven't been enforcing it yet. Hopefully we'll implement that in the near future : )
