### ISSUE TITLE
Sketch Image Replaste!

### ISSUE THREAD

**Issue by mheesakkers** [sketchplugins/plugin-directory#320]
I created a simple Sketch plugin for replacing images with a copied image of your clipboard.
https://github.com/mheesakkers/sketch-image-replaste
<img src="http://misha.studio/image-replaste/screencast-sketch-image-replaste.gif" alt="img" style="max-width:100%;">

**Comment by mlgbe** [comment]
the newest sketch  can't use CMD + SHIFT + Y anymore , how to solve it?

**Comment by mheesakkers** [comment]
Hi!

I just updated the plugin with a shortcut change: CMD + CTRL + I

Could you check if the update came through?

Thanks for notifying me ;)

All the best,
Misha
