### ISSUE TITLE
Question about changing background color of sketch

### ISSUE THREAD

**Issue by manaknight** [sketchplugins/plugin-directory#322]
Hello,
I don't know if this is the best place to post this but I'm having trouble finding out which object I should be dealing with.

I want to change the default sketch background color behind the artboards to black color instead of white. Which object should I be dealing with?

I'm at:

var sketch = context.api();
var doc = sketch.selectedDocument;
var page = doc.selectedPage;

Do I use document, page, artboard? 

All examples I see are changing an artboard, shape or something you create on top of the background.

**Comment by bomberstudios** [comment]
It's not possible to change that color using any API that is accessible via plugins, sorry
