### ISSUE TITLE
Order by last updated

### ISSUE THREAD

**Issue by DWilliames** [sketchplugins/plugin-directory#339]
# Feature Request

This list a great resource to find various plugins — however, now that this list has been around for quite some time, it becomes increasingly difficult to find new plugins. Especially when some of these plugins are no longer maintained, or no longer supported by the latest versions of Sketch.

This could be a great resource to constantly refer back to, to find new cool plugins; given that it is easy to see the newly added ones.

## Proposal

By default, have all the plugins ordered by most recently added/updated in the README.md file. Create an alternative README.md file (e.g. README_alphabetical.md) with the current alphabetical sorting — containing hyperlinks between them.

## Last Updated??

In regards to how the plugins are ordered; the term *'Last updated'* may be tricky to define. I'm not quite sure where the current value of `lastUpdated` in `plugins.json` came from — but we'd need to decide on the best way to define where the timestamp comes from. 

It could either be: 

- Last time it was updated/added to this directory (meaning, anytime a Plugin author updated their plugin, they would need to update `plugins.json` in this repo too)
- Last time the repository had changes (this would be trickier — involving a batch periodical lookup of each repo, but would provide the most value)

**Comment by bomberstudios** [comment]
Thanks for filing this. `lastUpdated` is, in fact, the date of the last push to the plugin repo (when there is one) and I recently made a script to keep it updated. 

Will see what I can do about sorting the README

**Comment by bomberstudios** [comment]
Added this on a recent commit, so closing!
