### ISSUE TITLE
run `rake` on a CI to make the process even easier

### ISSUE THREAD

**Issue by mathieudutour** [sketchplugins/plugin-directory#346]
we could hook travis or circleCI to this repo and generate the README automatically every time there is a push to the master branch

**Comment by bomberstudios** [comment]
I'll take a look at CircleCI to see if it can do what we need it to do (it would need to commit the changes to README.md back into the repo)

**Comment by mathieudutour** [comment]
yes it can run any script, just need to give him a github token with the rights to push to this repo

**Comment by bomberstudios** [comment]
Cool, I'll see where I get once I get back in front of a computer : )
