### ISSUE TITLE
Please re-add my "Arrange Artboards" and "Next/Previous Artboard" plugins

### ISSUE THREAD

**Issue by kenmoore** [sketchplugins/plugin-directory#350]
I very recently updated these plugins to the proper bundle format, please re-add them here.

Arrange Artboards:
https://github.com/kenmoore/sketch-arrange-artboards

Artboard (Next/Previous Artboard, Next/Previous Page):
https://github.com/kenmoore/sketch-artboard

Thank you!

**Comment by bomberstudios** [comment]
Thank _you_ for the updates : )
