### ISSUE TITLE
New plugin for Sketch to be added to the list

### ISSUE THREAD

**Issue by vconesa** [sketchplugins/plugin-directory#352]
https://github.com/vconesa/justinmind-sketch

**Comment by vconesa** [comment]
Excellent! What do we have to do to be listed in this page
https://sketchapp.com/extensions/plugins/ as well?


*Victor Conesa *| Product Manager
victor.conesa@justinmind.com
www.justinmind.com

**Comment by bomberstudios** [comment]
Will be updated on the next deploy of the site (I just scheduled it, so it should be there in a few minutes)

**Comment by vconesa** [comment]
Wow!! Que eficiencia!!! Sois unos cracks!


*Victor Conesa *| Product Manager
victor.conesa@justinmind.com
www.justinmind.com

**Comment by bomberstudios** [comment]
Vaya, gracias! 😊
