### ISSUE TITLE
Seca plugin

### ISSUE THREAD

**Issue by kristiyanP** [sketchplugins/plugin-directory#372]
Export for multiple platforms correctly for Sketch design based on`symbols` and components

https://github.com/iGenius-Srl/Seca

**Comment by bomberstudios** [comment]
I'm a bit confused… can you clarify why you forked and renamed the project instead of sending the original developer a pull request?

Thanks!

**Comment by kristiyanP** [comment]
Because this plugin fits our needs, it does not fit necessary the common use...

**Comment by bomberstudios** [comment]
Got it, adding! 👍
