### ISSUE TITLE
Add Sketch Material plugin to the list

### ISSUE THREAD

**Issue by websiddu** [sketchplugins/plugin-directory#398]
Please do add this to the list.. 
https://github.com/websiddu/sketch-material

Also I created a PR

**Comment by bomberstudios** [comment]
Added

**Comment by websiddu** [comment]
For some reason. This is not showing up in https://sketchapp.com/extensions/plugins/ or any other 3rd party tools like Sketchpacks or Sketch runner. 

I'm not sure what I'm doing wrong.

**Comment by bomberstudios** [comment]
You'll need to add the plugin to SketchPacks and SketchRunner yourself (check the docs at https://docs.sketchpacks.com and http://sketchrunner.com/help.html)

As for the website, it will be updated on the next deploy.
