### ISSUE TITLE
`disablecocoascriptpreprocessor` leads `Error` to lose it's stack traces

### ISSUE THREAD

**Issue by MrPeak** [sketchplugins/plugin-directory#417]
Hi @bomberstudios:

When I set `disablecocoascriptpreprocessor` to true in the `manifest.json`, the `error` which is the instance of `Error` will lose it's stack traces.

Is it a bug? Or you guys have other considerations？

> Link to [disablecocoascriptpreprocessor-and-error-stack](http://sketchplugins.com/d/265-disablecocoascriptpreprocessor-and-error-stack).

**Comment by bomberstudios** [comment]
Thanks for getting in touch. I'm going to close this issue, since it's not related with this repository, and will try to answer the question in the forum.

**Comment by MrPeak** [comment]
Fine, link to http://sketchplugins.com/d/265-disablecocoascriptpreprocessor-and-error-stack
