### ISSUE TITLE
New plugin released: p5.sketchplugin

### ISSUE THREAD

**Issue by jacopocolo** [sketchplugins/plugin-directory#449]
Repository url: https://github.com/jacopocolo/p5-sketchplugin

(And thanks!)

**Comment by bomberstudios** [comment]
No, _thank you_ for the amazing plugin!

**Comment by zhongerxin** [comment]
Repository url: https://github.com/zhongerxin/PinLog
a plugin that would help you find where had a change.
I tried use SKPM to publish but faild 
<img width="775" alt="wx20171127-224352 2x" src="https://user-images.githubusercontent.com/8215057/33272227-7de5a566-d3c4-11e7-8a0b-d1df4eb180d1.png">
, I pray to have a detailed Guides.
