### ISSUE TITLE
Add StyleClip

### ISSUE THREAD

**Issue by liawesomesaucer** [sketchplugins/plugin-directory#485]
[https://github.com/liawesomesaucer/StyleClip](https://github.com/liawesomesaucer/StyleClip)

**Comment by liawesomesaucer** [comment]
FYI, forked and tried to manually add it, but `rake` ended up removing an existing entry (Sketch Serve by Matt Curtis). Here's my diff after running `rake` after additions to `plugins.json`

![screenshot 2018-01-18 13 59 41](https://user-images.githubusercontent.com/8205461/35123620-e16cbee2-fc57-11e7-9e3a-34deefb1c4b0.png)
:

**Comment by bomberstudios** [comment]
No worries, we remove outdated plugins when running `rake`. I'll add your plugin right now : )
