### ISSUE TITLE
Travis for building repo?

### ISSUE THREAD

**Issue by pravdomil** [sketchplugins/plugin-directory#491]
Hi @bomberstudios do you consider use Travis for building the readme? So that if somebody adds new item to plugins.json it will build new readme and push updated version? Push to build in cloud.

I can create a PR for it.

**Comment by bomberstudios** [comment]
I'll be happy to merge a PR that does this, yes : )

**Comment by pravdomil** [comment]
Great.

- [ ] are you ok with node.js and javascript/typescript for build script?
- [ ] we need some travis sketch account + set of github tokens to update this repo (for now I can setup my personal travis and github)

I think that's all for now.

**Comment by pravdomil** [comment]
https://github.com/sketchplugins/plugin-directory/pull/578
