### ISSUE TITLE
Add Separate Shapes

### ISSUE THREAD

**Issue by PEZ** [sketchplugins/plugin-directory#497]
https://github.com/PEZ/SketchSeparateShapes

A plugin for ”boolean” separating two overlapping shapes. Like _divide_ in Adobe Illustrator's Pathfinder.

**Comment by PEZ** [comment]
It seems skpm created a pull request for this already: #496 

However, it has a merge conflict that I have no clue what it is about.

**Comment by bomberstudios** [comment]
I'll close the PR and add it myself : )
