### ISSUE TITLE
Sketch Isometric still not listed in Sketchapp website, hence cannot be downloaded from Runner

### ISSUE THREAD

**Issue by sureskumar** [sketchplugins/plugin-directory#505]
Hey Ale Muñoz,

Sketch Isometric is still not listed in Sketchapp website, hence cannot be downloaded from Runner :( Many people are frustrated and are asking me to fix this :) It will be super helpful if the website can be refreshed with the updated content. 

Cheers! 
Sures

**Comment by bomberstudios** [comment]
Apologies! Should be there now : )
