### ISSUE TITLE
New plugin: Flow Exporter

### ISSUE THREAD

**Issue by romannurik** [sketchplugins/plugin-directory#517]
https://github.com/romannurik/Sketch-FlowExporter

Built with skpm, so there's no `.sketchplugin` directory in the repo; is that an issue?

**Comment by ajilderda** [comment]
There is a `.sketchplugin` under releases ;)

**Comment by romannurik** [comment]
Didn't realize that was sufficient for all the tools that rely on this directory, that's awesome!

**Comment by romannurik** [comment]
Dup of #518
