### ISSUE TITLE
New plugin

### ISSUE THREAD

**Issue by pravdomil** [sketchplugins/plugin-directory#569]
https://github.com/pravdomil/Sketch-cats#readme

**Comment by levtolstoi** [comment]
https://github.com/sketchplugins/plugin-directory/blob/master/CONTRIBUTING.md

**Comment by pravdomil** [comment]
> # Sketch Plugin Directory
> 
> A list of Sketch plugins hosted at GitHub, in alphabetical order.
> 
> Note: **if you want to add yours, just open an issue with the URL**, or send a pull request.
