### ISSUE TITLE
Finder service for exporting multiple sketch files

### ISSUE THREAD

**Issue by josie-zx** [sketchplugins/plugin-directory#574]
I was looking for a sketch plugin to batch export PNGs of sketch pages across multiple files, but could only find one that exports on the current file, so I created this Finder service that works on multiple files. https://github.com/josie-zx/sketch-batch-png

It's not a sketch plugin per se, but it kind of acts as an extension to sketch, and works only on sketch files...so I was wondering if it would be allowed on this list.

**Comment by christianklotz** [comment]
Nice use of `sketchtool` 👍, thanks for sharing. The `README` is dynamically generated from the JSON and the JSON file is used by installers and for the website to list plugins only.

So I'm afraid this Automator workflow cannot be included in the list.
