### ISSUE TITLE
Sketch plugin to align and resize to the layout

### ISSUE THREAD

**Issue by KevinvBre** [sketchplugins/plugin-directory#587]
Hi,

I started playing around with the 'run script' option in Sketch and in the end thats what led me to try and build a plugin. It has been a journey so I hope you guys appreciate my work.

It's a simple plugin to match the x position of a layer with the x position of the Sketch layout.
https://github.com/KevinvBre/Align-and-resize-to-layout

Cheers,
Kevin

Note: I'm not used to using Github so I hope I'm doing this last part correctly. (Designer on a daily basis)

**Comment by bomberstudios** [comment]
Everything's good, just added it. Thanks for developing for Sketch!
