### ISSUE TITLE
https://github.com/eric-adstage/Sketch_RotateLine

### ISSUE THREAD

**Issue by eric-adstage** [sketchplugins/plugin-directory#63]
Surprisingly, this isn't an out of the box feature. Created the plugin to play with the API at the request of a user on the Sketch subreddit.

https://github.com/eric-adstage/Sketch_RotateLine
A simple plugin to allow line rotation within Sketch. Includes options to rotate a copy and whether to use relative (from current position) or absolute (from global position) rotation.

**Comment by bomberstudios** [comment]
Added it, but let it be known that you can rotate lines by selecting them and hitting the 'Rotate' toolbar icon : )

![rotate-line](https://cloud.githubusercontent.com/assets/3832/5600106/ff65ead6-92d3-11e4-934e-da9fabbadc2f.gif)

**Comment by eric-adstage** [comment]
Yes, but with that tool, you can't say "I want to rotate this line 34
degrees" - with my plugin, you can. :)

Eric Foster | AdStage <https://www.adstage.io/> Engineer/Support Team

Featured in Wall Street Journal
<http://blogs.wsj.com/venturecapital/2014/08/13/adstage-raises-6-3m-to-put-digital-ad-management-on-auto-pilot/>
, TechCrunch <http://techcrunch.com/2014/08/13/adstage-series-a/>, Fast
Company
<http://www.fastcompany.com/3013378/as-google-adsense-turns-10-an-upstart-wants-to-own-the-next-generation-of-web-ads>
, VentureBeat
<http://venturebeat.com/2014/08/13/adstage-rolls-out-a-tool-for-power-advertisers-and-nabs-6-25m/#>
, & MarketingLand
<http://marketingland.com/ad-management-platform-adstage-lands-6-25-million-series-funding-95791>

**Comment by eric-adstage** [comment]
I should probably add some screenshots to my repo readme to make that more clear though.

**Comment by eric-adstage** [comment]
Screenshots added, description and repo documentation updated. Hopefully its purpose is more clear now. :)

**Comment by bomberstudios** [comment]
Ah, great, wasn't very clear from the description. Thanks for taking the time to explain it better! : )
