### ISSUE TITLE
Add Primary Sync plugin

### ISSUE THREAD

**Issue by primaryapp** [sketchplugins/plugin-directory#666]
{
    "title": "Primary Sync",
    "description": "Sync your Sketch designs 💎 with Primary's user flows and design documents.",
    "name": "Primary Sync",
    "owner": "Primary-app",
    "author": "Primary",
    "appcast": "https://raw.githubusercontent.com/Primary-app/primary-sync/master/.appcast.xml",
    "homepage": "https://github.com/Primary-app/primary-sync",
    "lastUpdated": "2018-07-30 19:57:00 UTC"
  },

Thanks :)

**Comment by EstelleRigault** [comment]
Thanks @bomberstudios 🙌
