### ISSUE TITLE
Can you add my artboard renaming plugin

### ISSUE THREAD

**Issue by KevinvBre** [sketchplugins/plugin-directory#687]
Thanks for hard work!
I made a Sketch plugin that renames artboards using the pagename as a prefix and numbering everything in the same row. I've been using it a lot in combination with Jira tickets and Zeplin. Comes in really handy! Could you add it to the list?

The link:
https://github.com/KevinvBre/Sketch-Rename-Artboards

Cheers,
Kevin

**Comment by bomberstudios** [comment]
Sure! Thanks for developing for Sketch : )
